return {
	Title = "太祖绘卷(UI,商人,制造,筛选,操作,仓库优化)",
	Author = "TenMountainMoon&ElysianSunaker",
	Version = "1.0.10.0",
	GameVersion = "1.0.10.0",
	Source = 0,
	Description = "太吾绘卷正式版的UI太烂了!太难用了!所以我要化身祖国人,让这个绘卷变成我需要的样子!\n该MOD由“十山月”制作\n\n整合了多个优化的内容,包括UI紧凑,批量制造,批量购买,高级物品筛选\n\n●UI紧凑:在MOD设置里可以调整各个窗口界面的物品UI缩放,让你的电脑屏幕不再只显示十个物品——你想要什么样,就是什么样\n·压缩物品排序按钮:原本的排序按钮占了两行,还贼大!很明显这是给洋人设计的东西,但是这是我们自己的游戏,我们凭什么要为了别人的舒适度丢失自己的适用性!开启这个按钮,把排序压缩到一行!\n·容器紧凑化:允许你修改背包,库房交换,功法选择界面的缩放比例,偌大的电脑屏幕只显示十个物品真的很蠢!我们是电脑玩家,不是搓玻璃的!\n·默认卡片视图:官方的“详细”信息详细了个寂寞!和简略相比不仅没有多出有效信息,反而还把图标给压缩了,为什么默认的还是这个界面呢?所以开启这个选项,让“简略”视图作为默认的选项!\n\n●批量制造:在制造食物和药毒时,可以在界面右上角调整设置,然后打开制作按钮上方的批量制造,就可以快速做出你想要的食材了!\n·制作优化:徒手做饭是何意味,自动选择工具选择了个秋风萧瑟,开启它,自动选择最高级的工具!\n·自动最大数量:做饭做菜默认只生产一个,但是我们都知道人是铁饭是钢,一顿不吃饿得慌,只做一份怎么够吃?让生产永远保持在最大数量!\n·食窖/药房/幽室开启:如果你不喜欢,你可以关闭一些你不想应用这些设置的建筑\n·做菜/药/毒自动连续制作:如果你有大量的交易需求,你可以打开它,让每一次制作都会用完你新买的引子!\n·可配置是否包括行囊/私库/公库\n·可配置最低/最高的品级限制\n·可配置优先使用的工具品级\n·可配置是否允许徒手制作\n·可配置是否开启耐久保护(如果工具在下一次使用中会损毁,则停止批量制作)\n\n●批量购买:在商人的“购回”界面上下，可以找到批量购买和配置界面,根据你的需求批量购买食物和药毒的引子,让商人成为一个合格的批发商\n·可配置批量采购的最低/最高品级\n·可配置是否采购涨价/原价的物品\n·可配置是否采购未解锁商店的物品(例如三级商店未解锁时,关闭这个功能,避免在三级商店购买而消耗购买限额)\n\n●高级物品筛选:基于高级物品筛选逻辑的功能,让你再也不需要多点一下然后找半天\n·前置筛选:没人觉得那个筛选按钮又大又没意义吗？所以我把它删了!现在你可以直接看到一级的筛选项目！双击可以打开更高级的筛选界面!\n\n●记忆优化:之前的太吾明明是有记忆功能的,但是正式版给删了,这不好,所以我给做回来了\n·排序记忆:记住上一次的排序优先级(例如品级优先),下次打开的时候还是这个排序!\n·策略预设记忆:记住上一次我用的是什么策略,我不想多点一下\n·切磋模式记忆:我就想自动打所有的较艺,因为它真的很无聊\n\n●暂未加入,将来(大概率)会加入的功能:\n·快速转移-[shift+鼠标左键]即可快速转移/出售物品,让你不需要再多点一下!\n·在产业地块上于商人交易时，允许直接从货仓出售物品\n·[Shift+鼠标左键]同时筛选多个项目",
	FrontendPlugins = {
		[1] = "Front/BetterTaiwuScrollFrontend.dll",
	},
	BackendPlugins = {
		[1] = "Back/BetterTaiwuScrollBackend.dll",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "compact_sort_buttons",
			DisplayName = "压缩物品排序按钮",
			Description = "将物品界面的名称、品阶、数量、重量、耐久、价格等排序按钮压缩到更紧凑的一行布局。",
			GroupName = "UI优化",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "inline_filter_buttons",
			DisplayName = "前置一级筛选按钮",
			Description = "隐藏筛选入口框，将筛选面板的第一级选项前置到物品列表上方；选择具体分类时再打开后续筛选项。",
			GroupName = "UI优化",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "best_tool",
			DisplayName = "自动最优工具",
			Description = "制作时自动选择可用工具中品级最高、价值最高的工具。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "max_product_count",
			DisplayName = "自动最大数量",
			Description = "选择引子后自动把制作数量调整到当前可制作最大值。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "food_enabled",
			DisplayName = "食窖",
			Description = "食窖制作优化启用开关。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "medicine_enabled",
			DisplayName = "药房",
			Description = "药房制作优化启用开关。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "poison_enabled",
			DisplayName = "幽室",
			Description = "幽室炼毒优化启用开关。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "auto_select_food_material",
			DisplayName = "做菜连续自动选材",
			Description = "做菜完成刷新后自动选择第一个可用引子。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "auto_select_medicine_material",
			DisplayName = "制药连续自动选材",
			Description = "制药完成刷新后自动选择第一个可用引子。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "auto_select_poison_material",
			DisplayName = "炼毒连续自动选材",
			Description = "炼毒完成刷新后自动选择第一个可用引子。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "continuous_make_ui",
			DisplayName = "连续制作界面",
			Description = "在制作界面显示连续制作勾选框和设置入口。",
			GroupName = "制作优化",
			DefaultValue = true,
		},
		[12] = {
			SettingType = "Toggle",
			Key = "container_compact",
			DisplayName = "容器紧凑化",
			Description = "缩小背包、交换类界面和功法选择界面的卡片列表，提高单屏信息密度。",
			GroupName = "UI优化",
			DefaultValue = true,
		},
		[13] = {
			SettingType = "Slider",
			Key = "container_inventory_scale",
			DisplayName = "背包容器缩放(%)",
			Description = "角色行囊卡片列表的缩放比例。",
			GroupName = "UI优化",
			MinValue = 30,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 70,
		},
		[14] = {
			SettingType = "Slider",
			Key = "container_exchange_scale",
			DisplayName = "交换容器缩放(%)",
			Description = "仓库、交易、商店、送礼等交换类界面卡片列表的缩放比例。",
			GroupName = "UI优化",
			MinValue = 30,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 72,
		},
		[15] = {
			SettingType = "Slider",
			Key = "container_skill_scale",
			DisplayName = "功法选择缩放(%)",
			Description = "功法选择界面卡片列表的缩放比例。",
			GroupName = "UI优化",
			MinValue = 30,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 70,
		},
		[16] = {
			SettingType = "Toggle",
			Key = "container_default_card_mode",
			DisplayName = "默认卡片视图",
			Description = "支持列表/卡片切换的物品界面默认进入卡片视图。",
			GroupName = "UI优化",
			DefaultValue = true,
		},
		[17] = {
			SettingType = "Toggle",
			Key = "memory_filter_enabled",
			DisplayName = "记忆筛选",
			Description = "重新打开同类界面时恢复上一次使用的筛选条件。",
			GroupName = "记忆优化",
			DefaultValue = true,
		},
		[18] = {
			SettingType = "Toggle",
			Key = "memory_sort_enabled",
			DisplayName = "记忆排序",
			Description = "重新打开同类界面时恢复上一次使用的名称、品阶、数量等排序条件。",
			GroupName = "记忆优化",
			DefaultValue = true,
		},
		[19] = {
			SettingType = "Toggle",
			Key = "memory_strategy_preset_enabled",
			DisplayName = "记忆策略预设",
			Description = "技艺切磋选择策略时，记住每种技艺上一次选择的策略预设。",
			GroupName = "记忆优化",
			DefaultValue = true,
		},
		[20] = {
			SettingType = "Toggle",
			Key = "memory_lifeskill_auto_mode_enabled",
			DisplayName = "记忆切磋模式",
			Description = "技艺切磋开始时恢复上一次的自动或手动模式。",
			GroupName = "记忆优化",
			DefaultValue = true,
		},
		[21] = {
			SettingType = "Toggle",
			Key = "bulk_purchase_ui",
			DisplayName = "批量采购",
			Description = "在商人界面显示批量采购入口和设置按钮。",
			GroupName = "购买优化",
			DefaultValue = true,
		},
		[22] = {
			SettingType = "Toggle",
			Key = "shop_show_stock_page",
			DisplayName = "显示货仓",
			Description = "在商人界面的太吾物品页签中显示货仓，便于直接购买到货仓或从货仓出售物品。",
			GroupName = "购买优化",
			DefaultValue = true,
		},
		[23] = {
			SettingType = "Toggle",
			Key = "fast_transfer",
			DisplayName = "快速转移",
			Description = "按住Shift左键点击交换、商人、仓库等界面的物品时，直接转移/出售/买入最大可用数量，不打开数量选择框。",
			GroupName = "操作优化",
			DefaultValue = true,
		},
		[24] = {
			SettingType = "Toggle",
			Key = "invert_fast_transfer",
			DisplayName = "反转快速转移",
			Description = "开启后，普通左键点击物品即快速转移/出售/买入；按住Shift左键则保留原版数量选择。",
			GroupName = "操作优化",
			DefaultValue = false,
		},
		[25] = {
			SettingType = "Toggle",
			Key = "simplify_filter_icons",
			DisplayName = "图标简化",
			Description = "将物品筛选图标按钮简化为文字按钮，直接显示原悬浮提示中的筛选名称。",
			GroupName = "UI优化",
			DefaultValue = false,
		},
		[26] = {
			SettingType = "Toggle",
			Key = "simplified_filter_icon_underlines",
			DisplayName = "图标筛选下级提示",
			Description = "图标简化后，为仍有后续筛选菜单的文字按钮显示下划线。",
			GroupName = "UI优化",
			DefaultValue = false,
		},
		[27] = {
			SettingType = "Toggle",
			Key = "map_tile_icon_y_offset",
			DisplayName = "地图地块小图标上移",
			Description = "将世界地图地块上的人物数量、物品数量和挖掘/发现类小图标向地块内部上移，避免卡在地图夹缝。",
			GroupName = "UI优化",
			DefaultValue = true,
		},
		[28] = {
			SettingType = "Slider",
			Key = "map_tile_icon_y_offset_percent",
			DisplayName = "地图图标上移比例",
			Description = "按地块基础高度计算小图标纵向上移比例。0 表示不移动，35 为推荐值。",
			GroupName = "UI优化",
			MinValue = 0,
			MaxValue = 50,
			StepSize = 1,
			DefaultValue = 35,
		},
	},
	SettingGroups = {
		[1] = "UI优化",
		[2] = "制作优化",
		[3] = "记忆优化",
		[4] = "购买优化",
		[5] = "操作优化",
	},
	TagList = {
		[1] = "Optimizations",
		[2] = "Display",
		[3] = "Compatible Mods",
	},
	Visibility = 0,
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	UpdateLogList = {
		[1] = {
			Timestamp = 1782040470,
		},
		[2] = {
			Timestamp = 1782040564,
		},
		[3] = {
			Timestamp = 1782040716,
		},
		[4] = {
			Timestamp = 1782040749,
		},
		[5] = {
			Timestamp = 1782040778,
		},
	},
	FileId = 3749026190,
	Cover = "icon.png",
	WorkshopCover = "icon.png",
}
